name: Test fetch images

on:
  push:

  workflow_dispatch:
  
env:
  IMAGE: ghcr.io/cedrik-fuoco-adsk/openrv-buildpack-windows

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: List GitHub Package Images
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.actor }}
        run: |
          dir
          #docker pull ghcr.io/cedrik-fuoco-adsk/openrv-buildpack-windows:20250725
          docker images
