name: Test fetch images

on:
  push:

  workflow_dispatch:
  
env:
  BUILDPACK_IMAGE: ghcr.io/cedrik-fuoco-adsk/openrv-buildpack-windows:20250725

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: List GitHub Package Images
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.actor }}
        run: |
          dir
          $currentPath = (Get-Location).Path
          docker pull ghcr.io/cedrik-fuoco-adsk/openrv-buildpack-windows:20250725
          docker images
          docker run --rm `
            -v "${currentPath}:D:\workspace" `
            -w "D:\workspace" `
            ${{ env.BUILDPACK_IMAGE }} `
            powershell -Command @"
              Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser -Force
              ls
          "@
